### ISSUE TITLE
destroyById crashes the app when model with the id does not exist

### ISSUE THREAD

**Issue by sviox** [strongloop-community/loopback-connector-redis#38] opened 2016-10-27 13:06 UTC
Whenever I try to use destroyById with an ID that does not exist, Redis connector throws an error, which ultimately crashes the application. There is an error event handler inside the connector but that just generates another error, which is not handled.

I debugged the issue a bit and the error happens after the following line on redis.js returns [null] array:
`return handleKeys(null, [model + ':' + filter.where.id]);`

Later, the returned array is iterated and since result is null, an error is generated :

```
      results.forEach(function(result) {
        tasks.push(function(done) { br.destroy(model, result.id, done); });
      });
```

[TypeError: Cannot read property 'id' of null] 'error@context': {}

Later, this is what crashes the app:

```
TypeError: name.indexOf is not a function
at C:\source\x\node_modules\loopback-connector-redis\node_modules\strong-globalize\lib\helper.js:739:23
```

**Comment by superkhau** [comment] 2016-12-19 21:29
@sviox Can you provide a sample repo for us to clone and reproduce the issue on our end?

**Comment by superkhau** [comment] 2016-12-22 02:18
@sviox Ping

**Comment by superkhau** [comment] 2016-12-22 02:20
@setogit Might be an SG issue too, so you may want to take a look.

**Comment by sviox** [comment] 2017-01-05 11:13
Thank you b-admike for providing an example. My app was a bit complicated to strip down so I would have needed to create basically an empty application to demonstrate it just like you did.

**Comment by b-admike** [comment] 2017-01-06 23:46
You're welcome @sviox.

**Comment by gclyne** [comment] 2017-01-09 18:35
@b-admike I have a fix, if you can give it a test please.  I tested it myself, and it works.

**Comment by b-admike** [comment] 2017-01-10 03:09
@gclyne I have tested your fix and while my app doesn't crash, it still returns 200 status code and an empty array for the ids which don't exist. If that is the expected behaviour, then we are golden.

**Comment by gclyne** [comment] 2017-01-10 17:03
@b-admike Cool, so is it ok to go ahead and merge this fix or is there anyone else who should review this? @superkhau?

**Comment by b-admike** [comment] 2017-01-11 19:45
@gclyne I think it is safe to merge. @superkhau can pitch in

**Comment by superkhau** [comment] 2017-01-11 20:25
@gclyne I responded in the PR, can you add some tests? Should be able to land/release right after that is done.

@b-admike Can you do the initial review in the PR and ping me to do a final review? PTAL at https://github.com/strongloop-internal/loopback-knowledge-base/blob/master/triaging-pull-requests.md

**Comment by superkhau** [comment] 2017-01-11 20:26
cc @strongloop-community/loopback-managers We need a sprint 27 milestone for strongloop-community also.

**Comment by superkhau** [comment] 2017-01-11 20:26
@b-admike Please fill in the assignees, estimates, etc yourself next time.

**Comment by b-admike** [comment] 2017-01-12 21:05
Will do @superkhau and since the change is reviewed and merged, this issue can be closed as soon as @sviox also verifies it. We might also be able to close #44 since it seems like a related issue.

**Comment by superkhau** [comment] 2017-01-13 03:09
@b-admike Can you own the above? Feel free to close this issue after verifying with @sviox and close #44 after referencing the PR I landed or this issue for posterity.

**Comment by b-admike** [comment] 2017-04-06 21:50
@sviox I am closing this issue because I have verified the fix. However, if you see it again after using the master version of this repo (until next release), then we can investigate further. I have created a repro app [here](https://github.com/b-admike/repros-for-lb-issues/tree/master/redis38) that you can use.

**Closed** 2017-04-06 21:56 UTC
Labels: apex, bug
